### PR TITLE
Update to MOI v0.9

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by blegat** [comment]
@joehuchette What would you think of moving this package to JuliaOpt ?

**Comment by joehuchette** [comment]
Sounds good with me. Any potential objections from other JuliaOpt folks?

**Comment by blegat** [comment]
cc @mlubin @odow

**Comment by odow** [comment]
Candidate for jump-dev org?

**Comment by blegat** [comment]
> Candidate for jump-dev org?

Yes, it would be a good candidate to start testing the migration as it's still unreleased.

**Comment by mlubin** [comment]
Moving this to jump-dev SGTM.

**Comment by joehuchette** [comment]
OK. Let me know how I should handle the migration.

**Comment by blegat** [comment]
You can transfer it to me and I'll transfer it to jump-dev

**Comment by joehuchette** [comment]
I tried, but you have a repo with the same name (probably a fork), so it failed. If it's simply a matter of transfering to @jump-dev, I can do that directly as well.

**Comment by blegat** [comment]
Sounds good, try directly

**Comment by joehuchette** [comment]
Done

**Pull request merged**
